import { canonicalizeCircuit, componentPinPoints, deserializeCircuit, partByType, type CircuitComponent, type CircuitDocument, type ComponentType, type Point } from "@opencircuit/circuit-schema";
export { PARTS } from "@opencircuit/circuit-schema";

const NS="http://www.w3.org/2000/svg", GRID=8;
type Tool="select"|"wire"|ComponentType;
export interface EditorChange { document:CircuitDocument; reason:"edit"|"undo"|"redo"|"view" }
export interface SchematicEditorOptions { document:CircuitDocument; onChange?:(change:EditorChange)=>void; onSelection?:(components:string[],wires:string[])=>void; onMidWire?:(active:boolean)=>void }
const esc=(value:string)=>value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const idMax=(items:{id:string}[],prefix:string)=>Math.max(0,...items.map((item)=>item.id.startsWith(prefix)?Number(item.id.slice(prefix.length))||0:0));
const path=(points:Point[])=>points.map((point,index)=>`${index?"L":"M"}${point[0]} ${point[1]}`).join(" ");
function symbol(c:CircuitComponent):string { const type=c.type;switch(type){
 case"resistor":return `<path d="M-2 0h.45l.35-.7.7 1.4.7-1.4.7 1.4.65-.7H2"/>`;
 case"capacitor":return `<path d="M-2 0h1.55m0-1.2v2.4m.9-2.4v2.4M.45 0H2"/>`;
 case"inductor":return `<path d="M-2 0h.35c0-1 1-1 1 0s1 1 1 0 1-1 1 0 1 1 1 0H2"/>`;
 case"vsource":case"vsource_pulse":case"vsource_sine":return `<circle cx="0" cy="0" r="1.25"/><path d="M0-2v.75M0 1.25V2M-.45-.45h.9M0-.9v.9M-.45.55h.9"/>`;
 case"isource":return `<circle cx="0" cy="0" r="1.25"/><path d="M0-2v.75M0 1.25V2M0 .75V-.65m-.45.45L0-.7l.45.5"/>`;
 case"ground":return `<path d="M0 0v.55M-1 .55H1M-.65 1h1.3M-.3 1.45h.6"/>`;
 case"switch_spst":return `<path d="M-2 0h.7m2.6 0H2M-1.3 0L1.1 ${c.params?.closed?0:-1.1}"/><circle cx="-1.3" cy="0" r=".12"/><circle cx="1.3" cy="0" r=".12"/>`;
 case"potentiometer":return `<path d="M0-6v3.2l-.7.35 1.4.7-1.4.7 1.4.7-.7.35V6M4 0H.8m1.2-.5L.8 0 2 .5"/>`;
 case"diode":case"led":return `<path d="M0-2v.75M0 1.25V2M-1.15-1.25h2.3L0 1.25Zm-1.15 2.5h2.3${type==="led"?"M.8-1.2l1-.8m-.45 1.35 1-.8":""}"/>`;
 case"bjt_npn":case"bjt_pnp":return `<path d="M-2 0h.8m0-1.6v3.2m0-1.05L2-4m-3.2 3.45L2 4M1.1 2.7l.9 1.3-1.5-.35${type==="bjt_pnp"?"M1.55-3.65L.3-3.1l.85.85":""}"/>`;
 case"nmos":case"pmos":return `<path d="M-2 0h.8m.3-1.8v3.6m.5-3.2v3.2M-.4-1.25H2V-4M-.4 1.25H2V4${type==="pmos"?"M-1.2 0a.35.35 0 1 0 .01 0":""}"/>`;
 case"opamp_ideal":return `<path d="M-4-2h1M-4 2h1M4 0H3M-3-3L3 0-3 3Zm.7.7v.6m-.3-.3h.6m0 3h.6"/>`;
 }}
function transform(c:CircuitComponent):string{return `translate(${c.pos[0]} ${c.pos[1]}) rotate(${c.rot}) scale(${c.mirror?-1:1} 1)`;}
function compactWire(points:Point[]):Point[]{return points.filter((point,index)=>index===0||point[0]!==points[index-1]![0]||point[1]!==points[index-1]![1]).filter((point,index,array)=>index===0||index===array.length-1||!((array[index-1]![0]===point[0]&&point[0]===array[index+1]![0])||(array[index-1]![1]===point[1]&&point[1]===array[index+1]![1])));}

export class SchematicEditor {
 readonly element:SVGSVGElement; private doc:CircuitDocument;private tool:Tool="select";private selectedComponents=new Set<string>();private selectedWires=new Set<string>();private undoStack:string[]=[];private redoStack:string[]=[];private gestureSnapshot="";private wireStart:Point|undefined;private wirePreview:Point|undefined;private pan:Point;private zoom:number;private space=false;private drag:{kind:"component"|"box"|"pan";start:Point;origin?:Point;id?:string}|undefined;
 constructor(private readonly host:HTMLElement,private readonly options:SchematicEditorOptions){this.doc=structuredClone(options.document);this.pan=this.doc.view?.pan??[0,0];this.zoom=this.doc.view?.zoom??1;this.element=document.createElementNS(NS,"svg");this.element.classList.add("schematic-editor");this.element.tabIndex=0;this.element.setAttribute("aria-label","Circuit schematic editor");host.replaceChildren(this.element);this.bindRoot();this.render();}
 getDocument():CircuitDocument{return structuredClone(this.doc)}
 edit(mutator:(document:CircuitDocument)=>void):void{this.change(()=>mutator(this.doc))}
 setDocument(document:CircuitDocument,resetHistory=true):void{this.doc=structuredClone(document);this.pan=this.doc.view?.pan??[0,0];this.zoom=this.doc.view?.zoom??1;if(resetHistory){this.undoStack=[];this.redoStack=[];}this.clearSelection();this.render();}
 setTool(tool:Tool):void{this.tool=tool;this.wireStart=undefined;this.wirePreview=undefined;this.options.onMidWire?.(false);this.render();}
 getTool():Tool{return this.tool}
 selected():{components:string[];wires:string[]}{return{components:[...this.selectedComponents],wires:[...this.selectedWires]}}
 canUndo():boolean{return this.undoStack.length>0} canRedo():boolean{return this.redoStack.length>0}
 undo():void{const snapshot=this.undoStack.pop();if(!snapshot)return;this.redoStack.push(canonicalizeCircuit(this.doc));this.doc=deserializeCircuit(snapshot);this.clearSelection();this.render();this.emit("undo")}
 redo():void{const snapshot=this.redoStack.pop();if(!snapshot)return;this.undoStack.push(canonicalizeCircuit(this.doc));this.doc=deserializeCircuit(snapshot);this.clearSelection();this.render();this.emit("redo")}
 rotate():void{this.change(()=>{for(const id of this.selectedComponents){const c=this.doc.components.find((item)=>item.id===id);if(c)c.rot=((c.rot+90)%360) as CircuitComponent["rot"];}})}
 mirror():void{this.change(()=>{for(const id of this.selectedComponents){const c=this.doc.components.find((item)=>item.id===id);if(c)c.mirror=!c.mirror;}})}
 deleteSelected():void{this.change(()=>{this.doc.components=this.doc.components.filter((c)=>!this.selectedComponents.has(c.id));this.doc.wires=this.doc.wires.filter((w)=>!this.selectedWires.has(w.id));this.clearSelection();})}
 copy():string{const payload={components:this.doc.components.filter((c)=>this.selectedComponents.has(c.id)),wires:this.doc.wires.filter((w)=>this.selectedWires.has(w.id))};return JSON.stringify(payload)}
 paste(source?:string):void{const raw=source??sessionStorage.getItem("schemagic.clipboard")??"";if(!raw)return;try{const data=JSON.parse(raw) as {components:CircuitComponent[];wires:CircuitDocument["wires"]};this.change(()=>{this.clearSelection();let ci=idMax(this.doc.components,"c"),wi=idMax(this.doc.wires,"w");for(const original of data.components??[]){const c=structuredClone(original);c.id=`c${++ci}`;c.pos=[c.pos[0]+2,c.pos[1]+2];this.doc.components.push(c);this.selectedComponents.add(c.id);}for(const original of data.wires??[]){const w=structuredClone(original);w.id=`w${++wi}`;w.points=w.points.map(([x,y])=>[x+2,y+2]);this.doc.wires.push(w);this.selectedWires.add(w.id);}});}catch{}}
 copyToClipboard():void{const value=this.copy();sessionStorage.setItem("schemagic.clipboard",value);void navigator.clipboard?.writeText(value).catch(()=>undefined)}
 fit():void{const points=[...this.doc.components.map((c)=>c.pos),...this.doc.wires.flatMap((w)=>w.points)];if(!points.length){this.pan=[0,0];this.zoom=1;}else{const rect=this.host.getBoundingClientRect(),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs)-6,maxX=Math.max(...xs)+6,minY=Math.min(...ys)-6,maxY=Math.max(...ys)+6;this.zoom=Math.max(.25,Math.min(4,Math.min(rect.width/GRID/(maxX-minX),rect.height/GRID/(maxY-minY))));this.pan=[rect.width/2-(minX+maxX)/2*GRID*this.zoom,rect.height/2-(minY+maxY)/2*GRID*this.zoom];}this.saveView();this.render();}
 setWireStyle(id:string,style:{stroke:string;dash?:string;width?:number;opacity?:number}):void{const el=this.element.querySelector<SVGPathElement>(`[data-wire-id="${id}"]`);if(el){el.style.stroke=style.stroke;el.style.strokeDasharray=style.dash??"none";el.style.strokeWidth=String(style.width??1.8);el.style.opacity=String(style.opacity??1);}}
 setWireCurrent(id:string,current:number):void{const group=this.element.querySelector<SVGGElement>(`.editor-wire-group[data-wire-id="${id}"]`);if(!group)return;const magnitude=Math.abs(current);group.classList.toggle("current-active",magnitude>=1e-6);group.classList.toggle("current-reverse",current<0);if(magnitude>=1e-6){const u=Math.max(0,Math.min(1,Math.log10(magnitude/1e-6)/4));group.style.setProperty("--pulse-speed",`${(34-16*u)/(12+96*u)}s`);group.style.setProperty("--pulse-alpha",String(.25+.45*u));group.style.setProperty("--pulse-spacing",String(34-16*u));}}
 setLedBrightness(id:string,brightness:number):void{const el=this.element.querySelector<SVGCircleElement>(`[data-led-halo="${id}"]`);if(el){el.style.opacity=String(Math.max(0,Math.min(1,brightness))*.78);el.setAttribute("r",String(3+Math.max(0,Math.min(1,brightness))*5));}}
 exportSvg():string{const clone=this.element.cloneNode(true) as SVGSVGElement;clone.querySelectorAll(".editor-hit,.connection-node,.selection-box,.wire-preview").forEach((e)=>e.remove());clone.setAttribute("xmlns",NS);return `<?xml version="1.0" encoding="UTF-8"?>\n${new XMLSerializer().serializeToString(clone)}`;}
 private bindRoot():void{this.element.addEventListener("wheel",e=>{e.preventDefault();const before=this.toWorld(e.clientX,e.clientY);this.zoom=Math.max(.2,Math.min(6,this.zoom*Math.exp(-e.deltaY*.0015)));const rect=this.element.getBoundingClientRect();this.pan=[e.clientX-rect.left-before[0]*GRID*this.zoom,e.clientY-rect.top-before[1]*GRID*this.zoom];this.saveView();this.render();},{passive:false});
  this.element.addEventListener("pointerdown",e=>this.pointerDown(e));this.element.addEventListener("pointermove",e=>this.pointerMove(e));this.element.addEventListener("pointerup",e=>this.pointerUp(e));this.element.addEventListener("pointercancel",e=>this.pointerUp(e));
  this.element.addEventListener("keydown",e=>{if((e.target as Element).tagName==="INPUT")return;if(e.key===" "){this.space=true;e.preventDefault();}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?this.redo():this.undo();}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="y"){e.preventDefault();this.redo();}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="c"){e.preventDefault();this.copyToClipboard();}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="v"){e.preventDefault();this.paste();}else if(e.key.toLowerCase()==="r")this.rotate();else if(e.key.toLowerCase()==="x")this.mirror();else if(e.key.toLowerCase()==="f")this.fit();else if(e.key==="Delete"||e.key==="Backspace")this.deleteSelected();else if(e.key==="Escape")this.setTool("select");});this.element.addEventListener("keyup",e=>{if(e.key===" ")this.space=false;});}
 private pointerDown(e:PointerEvent):void{this.element.focus();const target=e.target as SVGElement;const world=this.snap(this.toWorld(e.clientX,e.clientY));if(this.space||e.button===1){this.drag={kind:"pan",start:[e.clientX,e.clientY],origin:[...this.pan]};this.element.setPointerCapture(e.pointerId);return;}
  if(this.tool==="wire"){if(!this.wireStart){this.wireStart=world;this.wirePreview=world;this.options.onMidWire?.(true);}else{this.change(()=>{const points=compactWire([this.wireStart!,[world[0],this.wireStart![1]],world]);if(points.length>=2)this.doc.wires.push({id:`w${idMax(this.doc.wires,"w")+1}`,points});});this.wireStart=undefined;this.wirePreview=undefined;this.options.onMidWire?.(false);}this.render();return;}
  if(this.tool!=="select"){this.change(()=>{const part=partByType(this.tool as ComponentType);const id=`c${idMax(this.doc.components,"c")+1}`;const component:CircuitComponent={id,type:part.type,pos:world,rot:0,mirror:false,label:{text:`${part.prefix}${id.slice(1)}`,offset:[0,-3]},...(part.defaultValue!==undefined?{value:part.defaultValue}:{}),...(part.type==="potentiometer"?{params:{t:.5}}:{})};this.doc.components.push(component);this.clearSelection();this.selectedComponents.add(id);});this.tool="select";this.render();return;}
  const componentId=target.closest<SVGGElement>("[data-component-id]")?.dataset.componentId;const wireId=target.closest<SVGElement>("[data-wire-id]")?.dataset.wireId;if(componentId){if(!e.shiftKey&&!this.selectedComponents.has(componentId))this.clearSelection();this.selectedComponents.add(componentId);const c=this.doc.components.find(item=>item.id===componentId)!;this.gestureSnapshot=canonicalizeCircuit(this.doc);this.drag={kind:"component",start:world,origin:[...c.pos],id:componentId};this.emitSelection();this.element.setPointerCapture(e.pointerId);this.render();}else if(wireId){if(!e.shiftKey)this.clearSelection();this.selectedWires.add(wireId);this.emitSelection();this.render();}else{if(!e.shiftKey)this.clearSelection();this.drag={kind:"box",start:world};this.element.setPointerCapture(e.pointerId);this.emitSelection();this.render();}}
 private pointerMove(e:PointerEvent):void{const world=this.snap(this.toWorld(e.clientX,e.clientY));if(this.wireStart){this.wirePreview=world;this.render();return;}if(!this.drag)return;if(this.drag.kind==="pan"){this.pan=[this.drag.origin![0]+e.clientX-this.drag.start[0],this.drag.origin![1]+e.clientY-this.drag.start[1]];this.render();return;}if(this.drag.kind==="component"){const c=this.doc.components.find(item=>item.id===this.drag!.id);if(c)c.pos=[this.drag.origin![0]+world[0]-this.drag.start[0],this.drag.origin![1]+world[1]-this.drag.start[1]];this.render();return;}this.wirePreview=world;this.render();}
 private pointerUp(e:PointerEvent):void{if(!this.drag)return;if(this.drag.kind==="component"&&this.gestureSnapshot&&this.gestureSnapshot!==canonicalizeCircuit(this.doc)){this.undoStack.push(this.gestureSnapshot);this.redoStack=[];this.emit("edit");}else if(this.drag.kind==="box"&&this.wirePreview){const a=this.drag.start,b=this.wirePreview,minX=Math.min(a[0],b[0]),maxX=Math.max(a[0],b[0]),minY=Math.min(a[1],b[1]),maxY=Math.max(a[1],b[1]);for(const c of this.doc.components)if(c.pos[0]>=minX&&c.pos[0]<=maxX&&c.pos[1]>=minY&&c.pos[1]<=maxY)this.selectedComponents.add(c.id);for(const w of this.doc.wires)if(w.points.some(p=>p[0]>=minX&&p[0]<=maxX&&p[1]>=minY&&p[1]<=maxY))this.selectedWires.add(w.id);this.emitSelection();}else if(this.drag.kind==="pan"){this.saveView();this.emit("view");}this.drag=undefined;this.wirePreview=undefined;this.gestureSnapshot="";if(this.element.hasPointerCapture(e.pointerId))this.element.releasePointerCapture(e.pointerId);this.render();}
 private toWorld(x:number,y:number):Point{const rect=this.element.getBoundingClientRect();return[(x-rect.left-this.pan[0])/GRID/this.zoom,(y-rect.top-this.pan[1])/GRID/this.zoom]}
 private snap([x,y]:Point):Point{return[Math.round(x),Math.round(y)]}
 private saveView():void{this.doc.view={pan:[...this.pan],zoom:this.zoom}}
 private change(fn:()=>void):void{const before=canonicalizeCircuit(this.doc);fn();const after=canonicalizeCircuit(this.doc);if(before!==after){this.undoStack.push(before);this.redoStack=[];this.emit("edit");}this.emitSelection();this.render();}
 private clearSelection():void{this.selectedComponents.clear();this.selectedWires.clear();this.emitSelection()}
 private emit(reason:EditorChange["reason"]):void{this.options.onChange?.({document:this.getDocument(),reason})}
 private emitSelection():void{this.options.onSelection?.([...this.selectedComponents],[...this.selectedWires])}
 private render():void{const nodes=new Map<string,number>();for(const w of this.doc.wires)for(const p of w.points)nodes.set(p.join(","),(nodes.get(p.join(","))??0)+1);for(const c of this.doc.components)for(const p of componentPinPoints(c))nodes.set(p.join(","),(nodes.get(p.join(","))??0)+1);const preview=this.wireStart&&this.wirePreview?compactWire([this.wireStart,[this.wirePreview[0],this.wireStart[1]],this.wirePreview]):[];let selection="";if(this.drag?.kind==="box"&&this.wirePreview){const a=this.drag.start,b=this.wirePreview;selection=`<rect class="selection-box" x="${Math.min(a[0],b[0])}" y="${Math.min(a[1],b[1])}" width="${Math.abs(a[0]-b[0])}" height="${Math.abs(a[1]-b[1])}"/>`;}
  this.element.innerHTML=`<defs><pattern id="editor-grid" width="1" height="1" patternUnits="userSpaceOnUse"><circle cx=".08" cy=".08" r=".035" class="grid-dot"/></pattern><radialGradient id="editor-led"><stop offset="0" stop-color="#BE7318" stop-opacity=".62"/><stop offset="1" stop-color="#BE7318" stop-opacity="0"/></radialGradient></defs><rect width="100%" height="100%" class="editor-bg"/><g class="editor-world" transform="translate(${this.pan[0]} ${this.pan[1]}) scale(${GRID*this.zoom})"><rect x="${-this.pan[0]/GRID/this.zoom}" y="${-this.pan[1]/GRID/this.zoom}" width="${this.host.clientWidth/GRID/this.zoom}" height="${this.host.clientHeight/GRID/this.zoom}" fill="url(#editor-grid)"/>${this.doc.wires.map(w=>`<g data-wire-id="${w.id}" class="editor-wire-group${this.selectedWires.has(w.id)?" selected":""}"><path data-wire-id="${w.id}" class="editor-wire" d="${path(w.points)}"/><path class="editor-current" d="${path(w.points)}"/><path data-wire-id="${w.id}" class="editor-hit" d="${path(w.points)}"/></g>`).join("")}${preview.length?`<path class="wire-preview" d="${path(preview)}"/>`:""}${this.doc.components.map(c=>`<g data-component-id="${c.id}" class="editor-component${this.selectedComponents.has(c.id)?" selected":""}" transform="${transform(c)}"><rect class="editor-component-hit" x="-3" y="-3" width="6" height="6"/>${c.type==="led"?`<circle data-led-halo="${c.id}" class="editor-led-halo" cx="0" cy="0" r="3" fill="url(#editor-led)" opacity="0"/>`:""}<g class="editor-symbol">${symbol(c)}</g><rect class="editor-selection" x="-3" y="-3" width="6" height="6"/><text class="editor-label" x="${c.label?.offset[0]??0}" y="${c.label?.offset[1]??-3}" transform="scale(${c.mirror?-1:1} 1) rotate(${-c.rot})">${esc(c.label?.text??c.id.toUpperCase())}</text></g>`).join("")}${[...nodes].map(([key,count])=>{const [x,y]=key.split(",");return `<circle class="connection-node${count>2?" junction":""}" cx="${x}" cy="${y}" r="${count > 2 ? .24 : .16}"/>`;}).join("")}${selection}</g>`;}
}
