// AUTO-GENERATED by scripts/generate-symbols.mjs — DO NOT EDIT.
// Artwork derived from the KiCad symbol libraries (CC-BY-SA 4.0), see vendor/kicad-symbols/README.md.
import type { ComponentType, Point } from "@opencircuit/circuit-schema";
export interface EditorSymbol {
  type: ComponentType;
  /** SVG inner markup, editor grid units, y-down, origin = component anchor. Classes only: sym-bg, sym-solid, sym-bold, pin-lead. */
  markup: string;
  /** Present only for potentiometer / switch_spst. */
  wiper?: string;
  lever?: string;
  leverPivot?: Point;
  /** Tight bounding box incl. pin leads: [minX, minY, maxX, maxY], grid units. */
  bbox: [number, number, number, number];
  /** Connection points; MUST deep-equal PARTS pins for this type, same order. */
  pins: Point[];
}
export const EDITOR_SYMBOLS: Record<ComponentType, EditorSymbol> = {
  "resistor": {
    type: "resistor",
    markup: "<path d=\"M-1.2 0 L-1.3333 0\"/><path d=\"M-1.2 0 L-1 -0.5333 L-0.8 0 L-0.6 0.5333 L-0.4 0\"/><path d=\"M-0.4 0 L-0.2 -0.5333 L0 0 L0.2 0.5333 L0.4 0\"/><path d=\"M0.4 0 L0.6 -0.5333 L0.8 0 L1 0.5333 L1.2 0\"/><path d=\"M1.2 0 L1.3333 0\"/><path class=\"pin-lead\" d=\"M-2 0 L-1.3333 0\"/><path class=\"pin-lead\" d=\"M2 0 L1.3333 0\"/>",
    bbox: [-2, -0.5333, 2, 0.5333],
    pins: [[-2, 0], [2, 0]],
  },
  "capacitor": {
    type: "capacitor",
    markup: "<path class=\"sym-bold\" d=\"M-0.4 1.0667 L-0.4 -1.0667\"/><path class=\"sym-bold\" d=\"M0.4 1.0667 L0.4 -1.0667\"/><path class=\"pin-lead\" d=\"M-2 0 L-0.5333 0\"/><path class=\"pin-lead\" d=\"M2 0 L0.5333 0\"/>",
    bbox: [-2, -1.0667, 2, 1.0667],
    pins: [[-2, 0], [2, 0]],
  },
  "inductor": {
    type: "inductor",
    markup: "<path d=\"M-1.3333 0 A0.3333 0.3333 0 0 1 -0.6667 0\"/><path d=\"M-0.6667 0 A0.3333 0.3333 0 0 1 0 0\"/><path d=\"M0 0 A0.3333 0.3333 0 0 1 0.6667 0\"/><path d=\"M0.6667 0 A0.3333 0.3333 0 0 1 1.3333 0\"/><path class=\"pin-lead\" d=\"M-2 0 L-1.3333 0\"/><path class=\"pin-lead\" d=\"M2 0 L1.3333 0\"/>",
    bbox: [-2, -0.3319, 2, 0],
    pins: [[-2, 0], [2, 0]],
  },
  "vsource": {
    type: "vsource",
    markup: "<circle class=\"sym-bg\" cx=\"0\" cy=\"0\" r=\"1\"/><path d=\"M-0.5 -0.1 L0.5 -0.1\"/><path d=\"M-0.3 0.1 L-0.5 0.1\"/><path d=\"M0.1 0.1 L-0.1 0.1\"/><path d=\"M0.5 0.1 L0.3 0.1\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -1\"/><path class=\"pin-lead\" d=\"M0 2 L0 1\"/>",
    bbox: [-1, -2, 1, 2],
    pins: [[0, -2], [0, 2]],
  },
  "vsource_pulse": {
    type: "vsource_pulse",
    markup: "<circle class=\"sym-bg\" cx=\"0\" cy=\"0\" r=\"1\"/><path d=\"M-0.8 0.3 L-0.55 0.3 L-0.45 -0.3 L-0.05 -0.3 L0.05 0.3 L0.45 0.3 L0.55 -0.3 L0.8 -0.3\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -1\"/><path class=\"pin-lead\" d=\"M0 2 L0 1\"/>",
    bbox: [-1, -2, 1, 2],
    pins: [[0, -2], [0, 2]],
  },
  "vsource_sine": {
    type: "vsource_sine",
    markup: "<circle class=\"sym-bg\" cx=\"0\" cy=\"0\" r=\"1\"/><path d=\"M-0.5 0 A0.25 0.25 0 0 1 0 0\"/><path d=\"M0.5 0 A0.25 0.25 0 0 1 0 0\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -1\"/><path class=\"pin-lead\" d=\"M0 2 L0 1\"/>",
    bbox: [-1, -2, 1, 2],
    pins: [[0, -2], [0, 2]],
  },
  "isource": {
    type: "isource",
    markup: "<circle class=\"sym-bg\" cx=\"0\" cy=\"0\" r=\"1\"/><path d=\"M-0.5 -0.1 L0.5 -0.1\"/><path d=\"M-0.3 0.1 L-0.5 0.1\"/><path d=\"M0.1 0.1 L-0.1 0.1\"/><path d=\"M0.5 0.1 L0.3 0.1\"/><path d=\"M-0.1 -0.7 L0 -0.5 L0.1 -0.7\"/><path d=\"M0 -0.5 L0 -0.9\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -1\"/><path class=\"pin-lead\" d=\"M0 2 L0 1\"/>",
    bbox: [-1, -2, 1, 2],
    pins: [[0, -2], [0, 2]],
  },
  "ground": {
    type: "ground",
    markup: "<path d=\"M0 0 L0 0.6667 L0.6667 0.6667 L0 1.3333 L-0.6667 0.6667 L0 0.6667\"/><path class=\"pin-lead\" d=\"M0 0 L0 0\"/>",
    bbox: [-0.6667, 0, 0.6667, 1.3333],
    pins: [[0, 0]],
  },
  "switch_spst": {
    type: "switch_spst",
    markup: "<circle cx=\"-0.8\" cy=\"0\" r=\"0.2\"/><circle cx=\"0.8\" cy=\"0\" r=\"0.2\"/><path class=\"pin-lead\" d=\"M-2 0 L-1 0\"/><path class=\"pin-lead\" d=\"M2 0 L1 0\"/>",
    lever: "<path d=\"M-0.6 -0.1 L0.6 -0.7\"/>",
    leverPivot: [-0.8, 0],
    bbox: [-2, -0.7, 2, 0.2],
    pins: [[-2, 0], [2, 0]],
  },
  "potentiometer": {
    type: "potentiometer",
    markup: "<path d=\"M0 -1.3333 L0 -1.2\"/><path d=\"M0 -1.2 L0.5333 -1 L0 -0.8 L-0.5333 -0.6 L0 -0.4\"/><path d=\"M0 -0.4 L0.5333 -0.2 L0 0 L-0.5333 0.2 L0 0.4\"/><path d=\"M0 0.4 L0.5333 0.6 L0 0.8 L-0.5333 1 L0 1.2\"/><path d=\"M0 1.2 L0 1.3333\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -1.3333\"/><path class=\"pin-lead\" d=\"M0 2 L0 1.3333\"/>",
    wiper: "<path class=\"sym-solid\" d=\"M0.6 0 L1.2 -0.2667 L1.2 0.2667 Z\"/><path d=\"M1.3333 0 L0.8 0\"/><path class=\"pin-lead\" d=\"M2 0 L1.3333 0\"/>",
    bbox: [-0.5333, -2, 2, 2],
    pins: [[0, -2], [2, 0], [0, 2]],
  },
  "diode": {
    type: "diode",
    markup: "<path d=\"M-0.6667 0.6667 L0.6667 0.6667\"/><path d=\"M-0.6667 -0.6667 L0.6667 -0.6667 L0 0.6667 Z\"/><path d=\"M0 -0.6667 L0 0.6667\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -0.6667\"/><path class=\"pin-lead\" d=\"M0 2 L0 0.6667\"/>",
    bbox: [-0.6667, -2, 0.6667, 2],
    pins: [[0, -2], [0, 2]],
  },
  "led": {
    type: "led",
    markup: "<path d=\"M0.4 1.6 L1.2 2.4 L1.2 2 L1.2 2.4 L0.8 2.4\"/><path d=\"M0.4 0.9333 L1.2 1.7333 L1.2 1.3333 L1.2 1.7333 L0.8 1.7333\"/><path d=\"M0 0.6667 L0 -0.6667\"/><path d=\"M0.6667 0.6667 L-0.6667 0.6667\"/><path d=\"M0.6667 -0.6667 L-0.6667 -0.6667 L0 0.6667 Z\"/><path class=\"pin-lead\" d=\"M0 -2 L0 -0.6667\"/><path class=\"pin-lead\" d=\"M0 2 L0 0.6667\"/>",
    bbox: [-0.6667, -2, 1.2, 2.4],
    pins: [[0, -2], [0, 2]],
  },
  "bjt_npn": {
    type: "bjt_npn",
    markup: "<path d=\"M-0.6667 0 L1 0\"/><path class=\"sym-bold\" d=\"M1 -1.125 L1 1.125 L1 1.125\"/><path d=\"M1 -0.375 L2 -1.5\"/><path d=\"M1 0.375 L2 1.5 L2 1.5\"/><circle cx=\"1.3333\" cy=\"0\" r=\"1.5698\"/><path class=\"sym-solid\" d=\"M1.3333 1.05 L1.6 0.75 L1.8667 1.35 L1.3333 1.05 Z\"/><path d=\"M2.1333 0.75 L2.1333 0.75\"/><path d=\"M2.1333 0.75 L2.1333 0.75\"/><path class=\"pin-lead\" d=\"M2 -3 L2 -1.5\"/><path class=\"pin-lead\" d=\"M-2 0 L-0.6667 0\"/><path class=\"pin-lead\" d=\"M2 3 L2 1.5\"/>",
    bbox: [-2, -3, 2.9031, 3],
    pins: [[2, -3], [-2, 0], [2, 3]],
  },
  "bjt_pnp": {
    type: "bjt_pnp",
    markup: "<path d=\"M-0.6667 0 L1 0\"/><path class=\"sym-bold\" d=\"M1 -1.125 L1 1.125 L1 1.125\"/><path d=\"M1 -0.375 L2 -1.5\"/><path d=\"M1 0.375 L2 1.5 L2 1.5\"/><circle cx=\"1.3333\" cy=\"0\" r=\"1.5698\"/><path class=\"sym-solid\" d=\"M1.8667 1.05 L1.6 1.35 L1.3333 0.75 L1.8667 1.05 Z\"/><path class=\"pin-lead\" d=\"M2 -3 L2 -1.5\"/><path class=\"pin-lead\" d=\"M-2 0 L-0.6667 0\"/><path class=\"pin-lead\" d=\"M2 3 L2 1.5\"/>",
    bbox: [-2, -3, 2.9031, 3],
    pins: [[2, -3], [-2, 0], [2, 3]],
  },
  "nmos": {
    type: "nmos",
    markup: "<path d=\"M0.8 -1.125 L0.8 1.125\"/><path d=\"M0.8 0 L-0.6667 0\"/><path d=\"M1.0667 -1.35 L1.0667 -0.75\"/><path d=\"M1.0667 -0.3 L1.0667 0.3\"/><path d=\"M1.0667 0.75 L1.0667 1.35\"/><path d=\"M1.0667 1.05 L2.4 1.05 L2.4 -1.05 L1.0667 -1.05\"/><path class=\"sym-solid\" d=\"M1.2 0 L1.7333 -0.225 L1.7333 0.225 Z\"/><circle cx=\"1.5333\" cy=\"0\" r=\"1.5556\"/><path d=\"M2 -1.5 L2 -1.05\"/><circle class=\"sym-solid\" cx=\"2\" cy=\"-1.05\" r=\"0.1414\"/><circle class=\"sym-solid\" cx=\"2\" cy=\"1.05\" r=\"0.1414\"/><path d=\"M2 1.5 L2 0 L1.0667 0\"/><path d=\"M2.1333 -0.3 L2.2 -0.225 L2.6 -0.225 L2.6667 -0.15\"/><path d=\"M2.4 -0.225 L2.2 0.15 L2.6 0.15 Z\"/><path class=\"pin-lead\" d=\"M2 -3 L2 -1.5\"/><path class=\"pin-lead\" d=\"M-2 0 L-0.6667 0\"/><path class=\"pin-lead\" d=\"M2 3 L2 1.5\"/>",
    bbox: [-2, -3, 3.089, 3],
    pins: [[2, -3], [-2, 0], [2, 3]],
  },
  "pmos": {
    type: "pmos",
    markup: "<path d=\"M0.8 -1.125 L0.8 1.125\"/><path d=\"M0.8 0 L-0.6667 0\"/><path d=\"M1.0667 -1.35 L1.0667 -0.75\"/><path d=\"M1.0667 -1.05 L2.4 -1.05 L2.4 1.05 L1.0667 1.05\"/><path d=\"M1.0667 -0.3 L1.0667 0.3\"/><path d=\"M1.0667 0.75 L1.0667 1.35\"/><circle cx=\"1.5333\" cy=\"0\" r=\"1.5556\"/><path class=\"sym-solid\" d=\"M1.8667 0 L1.3333 -0.225 L1.3333 0.225 Z\"/><path d=\"M2 -1.5 L2 -1.05\"/><circle class=\"sym-solid\" cx=\"2\" cy=\"-1.05\" r=\"0.1414\"/><circle class=\"sym-solid\" cx=\"2\" cy=\"1.05\" r=\"0.1414\"/><path d=\"M2 1.5 L2 0 L1.0667 0\"/><path d=\"M2.1333 0.3 L2.2 0.225 L2.6 0.225 L2.6667 0.15\"/><path d=\"M2.4 0.225 L2.2 -0.15 L2.6 -0.15 Z\"/><path class=\"pin-lead\" d=\"M2 -3 L2 -1.5\"/><path class=\"pin-lead\" d=\"M-2 0 L-0.6667 0\"/><path class=\"pin-lead\" d=\"M2 3 L2 1.5\"/>",
    bbox: [-2, -3, 3.089, 3],
    pins: [[2, -3], [-2, 0], [2, 3]],
  },
  "opamp_ideal": {
    type: "opamp_ideal",
    markup: "<path class=\"sym-bg\" d=\"M2.6667 0 L-2.6667 -4 L-2.6667 4 Z\"/><path d=\"M-2.5171 -2 L-2.1496 -2 M-2.3333 -2.2756 L-2.3333 -1.7244\"/><path d=\"M-2.5171 2 L-2.1496 2\"/><path class=\"pin-lead\" d=\"M-4 -2 L-2.6667 -2\"/><path class=\"pin-lead\" d=\"M-4 2 L-2.6667 2\"/><path class=\"pin-lead\" d=\"M4 0 L2.6667 0\"/>",
    bbox: [-4, -4, 4, 4],
    pins: [[-4, -2], [-4, 2], [4, 0]],
  },
};
