import type {
  DesignCandidateV2,
  PrimaryPartCustomizationSidecarV1,
  PrimaryPartCustomizedResultSidecarV1,
} from "@opencircuit/design-schema";
import type { DesignerPrimaryPartCustomizationTargetV1 } from "./contracts";
import { escapeHtml, formatIdentifier } from "./view";

export interface PrimaryPartCustomizationViewState {
  readonly sourceCandidate: Readonly<DesignCandidateV2>;
  readonly targets: readonly DesignerPrimaryPartCustomizationTargetV1[];
  readonly instruction?: Readonly<PrimaryPartCustomizationSidecarV1>;
  readonly customizedResult?: Readonly<PrimaryPartCustomizedResultSidecarV1>;
  readonly phase: "idle" | "loading_targets" | "targets_unavailable" | "evaluating" | "importing" | "verifying_receipt";
  readonly exportingArtifact?:
    | "customized_target_electrical_bom_csv"
    | "customized_target_structural_svg"
    | "customized_target_engineering_report_html"
    | "customized_target_structural_kicad"
    | "customized_target_behavioral_scenario_spice"
    | "customized_target_inspection_receipt";
}

function primary(candidate: Readonly<DesignCandidateV2>) {
  return candidate.components.find((component) => component.id === "primary");
}

export function renderPrimaryPartCustomization(
  state: Readonly<PrimaryPartCustomizationViewState> | undefined,
): string {
  if (state === undefined) return "";
  const sourcePrimary = primary(state.sourceCandidate);
  if (sourcePrimary === undefined) return "";
  const selectedTarget = state.instruction === undefined
    ? undefined
    : state.targets.find((target) => target.instruction.contentHash === state.instruction?.contentHash);
  const targetCandidate = state.customizedResult?.targetResultProjection.candidates[0];
  const targetPrimary = targetCandidate === undefined ? undefined : primary(targetCandidate);
  const policyCandidate = state.customizedResult?.constraintDecision.candidates[0];
  const blockedRules = policyCandidate?.rules.filter((rule) => rule.disposition === "blocked_failure" || rule.disposition === "blocked_unknown") ?? [];
  const targetsUnavailable = state.phase === "targets_unavailable";
  const mutationBusy = state.phase !== "idle" && !targetsUnavailable;
  const exportBusy = state.exportingArtifact !== undefined;
  const busy = mutationBusy || exportBusy;
  const loadingTargets = state.phase === "loading_targets";
  const targetOptions = loadingTargets
    ? `<option value="">Checking the installed catalog…</option>`
    : targetsUnavailable
    ? `<option value="">Target discovery unavailable</option>`
    : state.targets.length === 0
    ? `<option value="">No compatible admitted alternate</option>`
    : `<option value="">Choose an exact admitted profile</option>${state.targets.map((target) => (
        `<option value="${escapeHtml(target.instruction.contentHash)}"${target.instruction.contentHash === state.instruction?.contentHash ? " selected" : ""}>${escapeHtml(target.targetProfile.manufacturerId)} / ${escapeHtml(target.targetProfile.manufacturerPartNumber)}</option>`
      )).join("")}`;
  const transferActions = `<div class="designer-customization-actions" aria-label="Customization instruction and inspection receipt transfer"><button data-primary-customization-import${mutationBusy ? " disabled" : ""}>${state.instruction === undefined ? "Load instruction JSON" : "Replace instruction JSON"}</button><input data-primary-customization-file type="file" accept="application/json,.json" hidden${mutationBusy ? " disabled" : ""}><button data-customized-target-receipt-import aria-describedby="designer-customized-target-receipt-boundary"${busy || state.targets.length === 0 ? " disabled" : ""}>${state.phase === "verifying_receipt" ? "Verifying exact inspection receipt…" : "Verify inspection receipt JSON"}</button><input data-customized-target-receipt-file type="file" accept="application/json,.json" hidden${busy || state.targets.length === 0 ? " disabled" : ""}></div>`;
  const instructionPanel = state.instruction === undefined
    ? ""
    : `<div class="designer-customization-signature" data-primary-customization-signature><article><span>01 · SOURCE</span><strong>${escapeHtml(sourcePrimary.part.manufacturerId)} / ${escapeHtml(sourcePrimary.part.manufacturerPartNumber)}</strong><code>${escapeHtml(state.instruction.substitution.sourceProfile.profileId)}</code><code>${escapeHtml(state.instruction.substitution.sourceProfile.contentHash)}</code></article><i aria-hidden="true">→</i><article><span>02 · TARGET</span><strong>${escapeHtml(selectedTarget?.targetProfile.manufacturerId ?? "Transferred instruction")} / ${escapeHtml(selectedTarget?.targetProfile.manufacturerPartNumber ?? formatIdentifier(state.instruction.substitution.targetProfile.profileId))}</strong><code>${escapeHtml(state.instruction.substitution.targetProfile.profileId)}</code><code>${escapeHtml(state.instruction.substitution.targetProfile.contentHash)}</code></article><i aria-hidden="true">→</i><article><span>03 · POLICY</span><strong>${state.customizedResult === undefined ? "Awaiting installed regeneration" : policyCandidate?.eligible ? "Eligible under installed V3 policy" : "Ineligible under installed V3 policy"}</strong><code>${escapeHtml(state.instruction.context.constraintPolicy.contentHash)}</code><code>${state.customizedResult === undefined ? "target eligibility not yet evaluated" : escapeHtml(state.customizedResult.constraintDecision.contentHash)}</code></article></div><div class="designer-customization-actions"><button class="designer-primary-action" data-primary-customization-apply${mutationBusy || selectedTarget === undefined ? " disabled" : ""}>${state.phase === "evaluating" ? "Evaluating exact substitution…" : state.customizedResult === undefined ? "Evaluate substitution" : "Re-evaluate substitution"}</button><button data-primary-customization-download${mutationBusy ? " disabled" : ""}>Download instruction</button><button data-primary-customization-share${mutationBusy ? " disabled" : ""}>Create request + instruction URL</button><button data-primary-customization-reset${mutationBusy ? " disabled" : ""}>Reset to generated part</button></div>`;
  const targetArtifactActions = state.customizedResult === undefined
    ? ""
    : `<div class="designer-customization-actions" aria-label="Customized target-only exports and inspection receipt"><button data-customized-target-export="customized_target_electrical_bom_csv" aria-describedby="designer-customized-target-export-boundary"${busy ? " disabled" : ""}>${state.exportingArtifact === "customized_target_electrical_bom_csv" ? "Preparing electrical BOM inspection CSV…" : "Download electrical BOM inspection CSV"}</button><button data-customized-target-export="customized_target_structural_svg" aria-describedby="designer-customized-target-export-boundary"${busy ? " disabled" : ""}>${state.exportingArtifact === "customized_target_structural_svg" ? "Preparing structural schematic inspection SVG…" : "Download structural schematic inspection SVG"}</button><button data-customized-target-export="customized_target_engineering_report_html" aria-describedby="designer-customized-target-export-boundary designer-customized-target-report-boundary"${busy ? " disabled" : ""}>${state.exportingArtifact === "customized_target_engineering_report_html" ? "Preparing target engineering report HTML…" : "Download target engineering report HTML"}</button><button data-customized-target-export="customized_target_structural_kicad" aria-describedby="designer-customized-target-export-boundary designer-customized-target-kicad-boundary"${busy ? " disabled" : ""}>${state.exportingArtifact === "customized_target_structural_kicad" ? "Preparing target structural KiCad schematic…" : "Download target structural KiCad schematic"}</button><button data-customized-target-export="customized_target_behavioral_scenario_spice" aria-describedby="designer-customized-target-export-boundary designer-customized-target-spice-boundary"${busy ? " disabled" : ""}>${state.exportingArtifact === "customized_target_behavioral_scenario_spice" ? "Preparing target behavioral Scenario SPICE…" : "Download target behavioral Scenario SPICE"}</button><button data-customized-target-receipt-export aria-describedby="designer-customized-target-receipt-boundary"${busy ? " disabled" : ""}>${state.exportingArtifact === "customized_target_inspection_receipt" ? "Preparing inspection receipt JSON…" : "Download inspection receipt JSON"}</button></div>`;
  const resultPanel = state.customizedResult === undefined || targetCandidate === undefined || targetPrimary === undefined
    ? ""
    : `<section class="designer-customization-result" data-primary-customization-result aria-labelledby="designer-customization-result-title"><header><div><span class="designer-section-code">TARGET-ONLY PROJECTION · INSTALLED V3 POLICY</span><h3 id="designer-customization-result-title" tabindex="-1">${escapeHtml(targetPrimary.part.manufacturerId)} / ${escapeHtml(targetPrimary.part.manufacturerPartNumber)}</h3></div><span class="designer-chip" data-status="${policyCandidate?.eligible ? "ready" : "blocked"}">${policyCandidate?.eligible ? "Eligible" : "Ineligible"}</span></header><dl><div><dt>Target candidate</dt><dd><code>${escapeHtml(targetCandidate.id)}</code></dd></div><div><dt>V3 policy result</dt><dd>${policyCandidate?.eligible ? "eligible" : "ineligible"} · ${blockedRules.length} blocking rule${blockedRules.length === 1 ? "" : "s"}</dd></div><div><dt>Ranking</dt><dd>not recomputed</dd></div><div><dt>Selected-part model</dt><dd>not added</dd></div><div><dt>Commercial authority</dt><dd>not added</dd></div></dl>${blockedRules.length > 0 ? `<details><summary>Inspect blocking rules <span>${blockedRules.length}</span></summary><ul>${blockedRules.map((rule) => `<li><code>${escapeHtml(rule.ruleId)}</code><span>${escapeHtml(rule.truth)} · ${escapeHtml(rule.criticality)} · ${escapeHtml(rule.disposition)}</span></li>`).join("")}</ul></details>` : ""}<p id="designer-customized-target-export-boundary"><strong>The ordinary generated result is unchanged. Installed V3 decision: ${policyCandidate?.eligible ? "eligible" : "ineligible"}.</strong> These files describe only this exact target projection. They add no authority to the ordinary result, ranking, eligibility, simulation samples, commercial decisions, release, or attestation.</p><p id="designer-customized-target-report-boundary"><strong>The engineering report is for inspection only.</strong> It adds no release, physical-fidelity, or commercial authority.</p><p id="designer-customized-target-kicad-boundary"><strong>The KiCad schematic is structural only and its footprints stay empty.</strong> Opening it in external KiCad remains UNVERIFIED; it carries no KiCad or release attestation.</p><p id="designer-customized-target-spice-boundary"><strong>Scenario SPICE is the exact default behavioral input and is available only with zero omissions.</strong> It adds no selected-part model, samples, physical fidelity, ranking, or eligibility authority.</p><p><strong>The portable receipt binds only the exact BOM CSV and structural SVG by filename, MIME type, UTF-8 byte length, and SHA-256; the payloads are not included.</strong> Parsing and replay prove byte association only. A load confers no installed-context, ordinary-result, eligibility, ranking, simulation, commercial, or attestation authority; explicit verification against this exact regenerated source is required.</p>${targetArtifactActions}<code>${escapeHtml(state.customizedResult.contentHash)}</code></section>`;

  return `<section class="designer-customization" data-primary-customization aria-labelledby="designer-customization-title" aria-busy="${busy}"><header><div><span class="designer-section-code">ENGINEERING CHANGE ORDER · PRIMARY ROLE ONLY</span><h2 id="designer-customization-title" tabindex="-1">Primary-part substitution</h2><p>Choose a reviewed same-class, same-facts-schema profile. Robonyx will regenerate the exact pre-Pareto target and evaluate it under the installed production policy without changing the generated result.</p></div><span class="designer-chip" data-status="${loadingTargets ? "unknown" : state.targets.length > 0 ? "ready" : "blocked"}" role="status" aria-live="polite">${loadingTargets ? "Checking catalog" : targetsUnavailable ? "Discovery unavailable" : `${state.targets.length} compatible`}</span></header>${transferActions}<p id="designer-customized-target-receipt-boundary" class="designer-export-gate">Inspection receipts are inert portable integrity data until explicitly verified against this exact regenerated source. They never regenerate a source automatically or transfer ordinary-result, ranking, simulation, commercial, or attestation authority.</p><label>Reviewed target profile<select data-primary-customization-target${mutationBusy || state.targets.length === 0 ? " disabled" : ""}>${targetOptions}</select></label>${targetsUnavailable ? `<p class="designer-customization-empty">Exact compatible-target discovery is unavailable because the structural preview could not be verified.</p>` : !loadingTargets && state.targets.length === 0 ? `<p class="designer-customization-empty">No exact same-recipe primary alternate with the same facts schema is admitted in the installed catalog.</p>` : ""}${instructionPanel}<p class="designer-export-gate">The instruction is inert transfer data until explicit installed regeneration. Ordinary ranking, candidate order, and export authority remain bound to the original generated result.</p>${resultPanel}</section>`;
}
