import { profileEvidence } from "./evidence";
import type {
  CapacitorProfile,
  ExternalControllerProfile,
  InductorProfile,
  IntegratedRegulatorProfile,
  PowerMosfetProfile,
  ResistorProfile,
  SyntheticBuckCatalog,
  SyntheticProfileBase,
} from "./types";

function deepFreeze<T>(value: T): Readonly<T> {
  if (value && typeof value === "object") {
    Object.freeze(value);
    for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  }
  return value;
}

function syntheticBase(
  profileId: string,
  manufacturerId: string,
  manufacturerPartNumber: string,
  displayName: string,
  areaM2: number,
): SyntheticProfileBase {
  return {
    profileId,
    profileKind: "synthetic_test_fixture",
    displayName,
    part: { manufacturerId, manufacturerPartNumber },
    evidence: profileEvidence(profileId),
    areaM2,
  };
}

const integratedRegulators: IntegratedRegulatorProfile[] = [
  {
    ...syntheticBase("synthetic.integrated.alpha-18v-4a", "synthetic-power-alpha", "SYN-P1-ALPHA", "Synthetic Alpha 18 V / 4 A regulator", 32e-6),
    topology: "integrated",
    inputVoltageMinV: 4.5,
    inputVoltageMaxV: 18,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 12,
    outputCurrentMaxA: 4,
    currentLimitA: 4.8,
    switchingFrequencyMinHz: 300_000,
    switchingFrequencyRecommendedHz: 500_000,
    switchingFrequencyMaxHz: 1_200_000,
    minimumOnTimeS: 80e-9,
    minimumOffTimeS: 100e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1.5e-3,
    thermalResistanceKPerW: 35,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    highSideResistanceOhm: 0.05,
    lowSideResistanceOhm: 0.03,
    riseTimeS: 10e-9,
    fallTimeS: 8e-9,
  },
  {
    ...syntheticBase("synthetic.integrated.beta-24v-4a5", "synthetic-power-beta", "SYN-P1-BETA", "Synthetic Beta 24 V / 4.5 A regulator", 24e-6),
    topology: "integrated",
    inputVoltageMinV: 5,
    inputVoltageMaxV: 24,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 14,
    outputCurrentMaxA: 4.5,
    currentLimitA: 5,
    switchingFrequencyMinHz: 400_000,
    switchingFrequencyRecommendedHz: 750_000,
    switchingFrequencyMaxHz: 1_500_000,
    minimumOnTimeS: 70e-9,
    minimumOffTimeS: 90e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1.8e-3,
    thermalResistanceKPerW: 45,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    highSideResistanceOhm: 0.06,
    lowSideResistanceOhm: 0.025,
    riseTimeS: 8e-9,
    fallTimeS: 8e-9,
  },
  {
    ...syntheticBase("synthetic.integrated.gamma-20v-3a8", "synthetic-power-gamma", "SYN-P1-GAMMA", "Synthetic Gamma 20 V / 3.8 A regulator", 18e-6),
    topology: "integrated",
    inputVoltageMinV: 4.5,
    inputVoltageMaxV: 20,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 10,
    outputCurrentMaxA: 3.8,
    currentLimitA: 4.5,
    switchingFrequencyMinHz: 300_000,
    switchingFrequencyRecommendedHz: 1_000_000,
    switchingFrequencyMaxHz: 1_200_000,
    minimumOnTimeS: 90e-9,
    minimumOffTimeS: 120e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1.2e-3,
    thermalResistanceKPerW: 55,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    highSideResistanceOhm: 0.07,
    lowSideResistanceOhm: 0.03,
    riseTimeS: 6e-9,
    fallTimeS: 7e-9,
  },
  {
    ...syntheticBase("synthetic.integrated.reject-vin-15v", "synthetic-power-reject", "SYN-P1-REJECT-VIN", "Synthetic rejected 15 V regulator", 20e-6),
    topology: "integrated",
    inputVoltageMinV: 4.5,
    inputVoltageMaxV: 15,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 10,
    outputCurrentMaxA: 4,
    currentLimitA: 4.8,
    switchingFrequencyMinHz: 300_000,
    switchingFrequencyRecommendedHz: 600_000,
    switchingFrequencyMaxHz: 1_000_000,
    minimumOnTimeS: 80e-9,
    minimumOffTimeS: 100e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1.5e-3,
    thermalResistanceKPerW: 45,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    highSideResistanceOhm: 0.05,
    lowSideResistanceOhm: 0.03,
    riseTimeS: 8e-9,
    fallTimeS: 8e-9,
  },
  {
    ...syntheticBase("synthetic.integrated.reject-current-2a", "synthetic-power-reject", "SYN-P1-REJECT-I", "Synthetic rejected 2 A regulator", 16e-6),
    topology: "integrated",
    inputVoltageMinV: 4.5,
    inputVoltageMaxV: 24,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 10,
    outputCurrentMaxA: 2,
    currentLimitA: 2.5,
    switchingFrequencyMinHz: 300_000,
    switchingFrequencyRecommendedHz: 800_000,
    switchingFrequencyMaxHz: 1_200_000,
    minimumOnTimeS: 80e-9,
    minimumOffTimeS: 100e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1e-3,
    thermalResistanceKPerW: 45,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    highSideResistanceOhm: 0.06,
    lowSideResistanceOhm: 0.035,
    riseTimeS: 8e-9,
    fallTimeS: 8e-9,
  },
  {
    ...syntheticBase("synthetic.integrated.reject-off-time", "synthetic-power-reject", "SYN-P1-REJECT-TOFF", "Synthetic rejected slow off-time regulator", 22e-6),
    topology: "integrated",
    inputVoltageMinV: 4.5,
    inputVoltageMaxV: 24,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 10,
    outputCurrentMaxA: 4,
    currentLimitA: 5,
    switchingFrequencyMinHz: 800_000,
    switchingFrequencyRecommendedHz: 1_200_000,
    switchingFrequencyMaxHz: 1_500_000,
    minimumOnTimeS: 80e-9,
    minimumOffTimeS: 800e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1.5e-3,
    thermalResistanceKPerW: 45,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    highSideResistanceOhm: 0.05,
    lowSideResistanceOhm: 0.03,
    riseTimeS: 8e-9,
    fallTimeS: 8e-9,
  },
  {
    ...syntheticBase("synthetic.integrated.reject-control-unknown", "synthetic-power-reject", "SYN-P1-REJECT-CONTROL", "Synthetic rejected regulator with missing control evidence", 19e-6),
    topology: "integrated",
    inputVoltageMinV: 4.5,
    inputVoltageMaxV: 24,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 10,
    outputCurrentMaxA: 4,
    currentLimitA: 5,
    switchingFrequencyMinHz: 300_000,
    switchingFrequencyRecommendedHz: 600_000,
    switchingFrequencyMaxHz: 1_200_000,
    minimumOnTimeS: 80e-9,
    minimumOffTimeS: 100e-9,
    feedbackReferenceV: 0.8,
    quiescentCurrentA: 1.5e-3,
    thermalResistanceKPerW: 45,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "missing",
    highSideResistanceOhm: 0.05,
    lowSideResistanceOhm: 0.03,
    riseTimeS: 8e-9,
    fallTimeS: 8e-9,
  },
];

const externalControllers: ExternalControllerProfile[] = [
  {
    ...syntheticBase("synthetic.controller.delta-60v", "synthetic-power-delta", "SYN-P2-DELTA", "Synthetic Delta 60 V controller", 36e-6),
    topology: "external-controller",
    inputVoltageMinV: 6,
    inputVoltageMaxV: 60,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 36,
    outputCurrentMaxA: 8,
    currentLimitA: 7,
    switchingFrequencyMinHz: 100_000,
    switchingFrequencyRecommendedHz: 200_000,
    switchingFrequencyMaxHz: 600_000,
    minimumOnTimeS: 100e-9,
    minimumOffTimeS: 150e-9,
    feedbackReferenceV: 1.2,
    quiescentCurrentA: 3e-3,
    thermalResistanceKPerW: 50,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    gateDriveVoltageV: 7.5,
    gateSourceCurrentA: 2,
    gateSinkCurrentA: 2,
    controllerLossW: 0.18,
  },
  {
    ...syntheticBase("synthetic.controller.epsilon-65v", "synthetic-power-epsilon", "SYN-P2-EPSILON", "Synthetic Epsilon 65 V controller", 24e-6),
    topology: "external-controller",
    inputVoltageMinV: 8,
    inputVoltageMaxV: 65,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 40,
    outputCurrentMaxA: 10,
    currentLimitA: 8,
    switchingFrequencyMinHz: 150_000,
    switchingFrequencyRecommendedHz: 350_000,
    switchingFrequencyMaxHz: 750_000,
    minimumOnTimeS: 80e-9,
    minimumOffTimeS: 110e-9,
    feedbackReferenceV: 1.2,
    quiescentCurrentA: 2.5e-3,
    thermalResistanceKPerW: 45,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    gateDriveVoltageV: 8.5,
    gateSourceCurrentA: 1.5,
    gateSinkCurrentA: 1.8,
    controllerLossW: 0.24,
  },
  {
    ...syntheticBase("synthetic.controller.reject-vin-48v", "synthetic-power-reject", "SYN-P2-REJECT-VIN", "Synthetic rejected 48 V controller", 20e-6),
    topology: "external-controller",
    inputVoltageMinV: 6,
    inputVoltageMaxV: 48,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 36,
    outputCurrentMaxA: 8,
    currentLimitA: 7,
    switchingFrequencyMinHz: 100_000,
    switchingFrequencyRecommendedHz: 250_000,
    switchingFrequencyMaxHz: 600_000,
    minimumOnTimeS: 100e-9,
    minimumOffTimeS: 150e-9,
    feedbackReferenceV: 1.2,
    quiescentCurrentA: 3e-3,
    thermalResistanceKPerW: 50,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "synthetic_bounded_model",
    gateDriveVoltageV: 7.5,
    gateSourceCurrentA: 2,
    gateSinkCurrentA: 2,
    controllerLossW: 0.18,
  },
  {
    ...syntheticBase("synthetic.controller.reject-control-unknown", "synthetic-power-reject", "SYN-P2-REJECT-CONTROL", "Synthetic rejected controller with missing control evidence", 22e-6),
    topology: "external-controller",
    inputVoltageMinV: 6,
    inputVoltageMaxV: 65,
    outputVoltageMinV: 0.8,
    outputVoltageMaxV: 36,
    outputCurrentMaxA: 8,
    currentLimitA: 7,
    switchingFrequencyMinHz: 100_000,
    switchingFrequencyRecommendedHz: 250_000,
    switchingFrequencyMaxHz: 600_000,
    minimumOnTimeS: 100e-9,
    minimumOffTimeS: 150e-9,
    feedbackReferenceV: 1.2,
    quiescentCurrentA: 3e-3,
    thermalResistanceKPerW: 50,
    maximumJunctionTemperatureK: 423.15,
    controlEvidence: "missing",
    gateDriveVoltageV: 7.5,
    gateSourceCurrentA: 2,
    gateSinkCurrentA: 2,
    controllerLossW: 0.18,
  },
];

const mosfets: PowerMosfetProfile[] = [
  {
    ...syntheticBase("synthetic.mosfet.eta-80v-low-r", "synthetic-power-eta", "SYN-FET-ETA", "Synthetic Eta 80 V low-resistance MOSFET", 30e-6),
    drainSourceVoltageV: 80,
    continuousCurrentA: 30,
    resistanceOhm: 0.012,
    resistanceGateVoltageV: 7.5,
    totalGateChargeC: 35e-9,
    riseTimeS: 15e-9,
    fallTimeS: 12e-9,
    thermalResistanceKPerW: 28,
    maximumJunctionTemperatureK: 423.15,
  },
  {
    ...syntheticBase("synthetic.mosfet.theta-100v-low-qg", "synthetic-power-theta", "SYN-FET-THETA", "Synthetic Theta 100 V low-charge MOSFET", 20e-6),
    drainSourceVoltageV: 100,
    continuousCurrentA: 25,
    resistanceOhm: 0.018,
    resistanceGateVoltageV: 8,
    totalGateChargeC: 22e-9,
    riseTimeS: 10e-9,
    fallTimeS: 9e-9,
    thermalResistanceKPerW: 35,
    maximumJunctionTemperatureK: 423.15,
  },
  {
    ...syntheticBase("synthetic.mosfet.reject-60v", "synthetic-power-reject", "SYN-FET-REJECT-60V", "Synthetic rejected 60 V MOSFET", 18e-6),
    drainSourceVoltageV: 60,
    continuousCurrentA: 30,
    resistanceOhm: 0.01,
    resistanceGateVoltageV: 7.5,
    totalGateChargeC: 20e-9,
    riseTimeS: 9e-9,
    fallTimeS: 9e-9,
    thermalResistanceKPerW: 30,
    maximumJunctionTemperatureK: 423.15,
  },
];

const inductors: InductorProfile[] = [
  ["3u3", 3.3e-6, 5.5, 4.5, 0.018, 0.08, 16e-6],
  ["4u7", 4.7e-6, 5.2, 4.5, 0.022, 0.07, 18e-6],
  ["5u6", 5.6e-6, 5.2, 4.5, 0.024, 0.07, 20e-6],
  ["8u2", 8.2e-6, 5.2, 4.5, 0.028, 0.06, 24e-6],
  ["18u", 18e-6, 8, 6.5, 0.02, 0.16, 38e-6],
  ["33u", 33e-6, 8, 6.5, 0.025, 0.18, 48e-6],
].map(([suffix, inductanceH, saturationCurrentA, rmsCurrentA, dcResistanceOhm, coreLossWAtFixturePoint, areaM2]) => {
  const profileId = `synthetic.inductor.${String(suffix)}`;
  return {
    ...syntheticBase(profileId, "synthetic-passives", `SYN-L-${String(suffix).toUpperCase()}`, `Synthetic ${String(suffix)} power inductor`, Number(areaM2)),
    inductanceH: Number(inductanceH),
    saturationCurrentA: Number(saturationCurrentA),
    rmsCurrentA: Number(rmsCurrentA),
    dcResistanceOhm: Number(dcResistanceOhm),
    coreLossWAtFixturePoint: Number(coreLossWAtFixturePoint),
  };
});

const capacitors: CapacitorProfile[] = [
  {
    ...syntheticBase("synthetic.capacitor.input-25v", "synthetic-passives", "SYN-CIN-25V", "Synthetic 10 uF / 25 V input capacitor", 10e-6),
    role: "input",
    nominalCapacitanceF: 10e-6,
    effectiveCapacitanceF: 5.5e-6,
    estimatedBiasDeratingRatio: null,
    voltageRatingV: 25,
    esrOhm: 0.01,
    rippleCurrentA: 3,
  },
  {
    ...syntheticBase("synthetic.capacitor.input-100v", "synthetic-passives", "SYN-CIN-100V", "Synthetic 4.7 uF / 100 V input capacitor", 20e-6),
    role: "input",
    nominalCapacitanceF: 4.7e-6,
    effectiveCapacitanceF: 2.5e-6,
    estimatedBiasDeratingRatio: null,
    voltageRatingV: 100,
    esrOhm: 0.018,
    rippleCurrentA: 3,
  },
  {
    ...syntheticBase("synthetic.capacitor.output-known-10v", "synthetic-passives", "SYN-COUT-10V", "Synthetic 22 uF / 10 V output capacitor with bias evidence", 12e-6),
    role: "output",
    nominalCapacitanceF: 22e-6,
    effectiveCapacitanceF: 12e-6,
    estimatedBiasDeratingRatio: null,
    voltageRatingV: 10,
    esrOhm: 0.008,
    rippleCurrentA: 4,
  },
  {
    ...syntheticBase("synthetic.capacitor.output-nominal-only-16v", "synthetic-passives", "SYN-COUT-NOMINAL", "Synthetic 12 uF / 16 V nominal-only output capacitor", 8e-6),
    role: "output",
    nominalCapacitanceF: 14e-6,
    effectiveCapacitanceF: null,
    estimatedBiasDeratingRatio: 0.5,
    voltageRatingV: 16,
    esrOhm: 0.006,
    rippleCurrentA: 3.5,
  },
  {
    ...syntheticBase("synthetic.capacitor.output-known-25v", "synthetic-passives", "SYN-COUT-25V", "Synthetic 22 uF / 25 V output capacitor with bias evidence", 18e-6),
    role: "output",
    nominalCapacitanceF: 22e-6,
    effectiveCapacitanceF: 15e-6,
    estimatedBiasDeratingRatio: null,
    voltageRatingV: 25,
    esrOhm: 0.015,
    rippleCurrentA: 4,
  },
];

const resistorValues = [10_000, 30_100, 52_300, 90_900, 110_000, 140_000];
const resistors: ResistorProfile[] = resistorValues.map((resistanceOhm) => {
  const suffix = String(resistanceOhm);
  const profileId = `synthetic.resistor.${suffix}`;
  return {
    ...syntheticBase(profileId, "synthetic-passives", `SYN-R-${suffix}`, `Synthetic ${suffix} ohm feedback resistor`, 1e-6),
    resistanceOhm,
    toleranceRatio: 0.01,
    voltageRatingV: 75,
    powerRatingW: 0.1,
  };
});

export const SYNTHETIC_BUCK_TEST_CATALOG: SyntheticBuckCatalog = deepFreeze({
  catalogKind: "synthetic_test_fixture",
  version: "designer-v1-reference.1",
  integratedRegulators,
  externalControllers,
  mosfets,
  inductors,
  capacitors,
  resistors,
});
