import { designProfileId, type DesignProfileV1, type PartClassId } from "@opencircuit/design-library";
import { adaptDesignRecipeV1ToV2,calculateElectricalDesignContextManifestV2ContentHash,calculateElectricalRankingPolicyV2ContentHash,calculateReviewedProfileCatalogV2ContentHash,getInstalledCompilerImplementationRefV2,type DesignGenerationV2,type ElectricalDesignContextManifestV2,type ElectricalMetricDeclarationV2,type ElectricalRankingPolicyV2,type LegacyProfileIdentityV2,type ReviewedProfileCatalogV2 } from "@opencircuit/design-engine";
import { generateElectricalDesignV2ForTesting,type GenerateElectricalTestContextV2 } from "@opencircuit/design-engine/v2-testing";
import { compareDesignV2Tokens,type BuckDesignRequestV2 } from "@opencircuit/design-schema";
import { SYNTHETIC_BUCK_TEST_CATALOG } from "./catalog";
import { BUCK_RECIPES } from "./recipe";

const declarations:ElectricalMetricDeclarationV2[]=[
  ["power.board-area","m2"],["power.bom-line-count","count"],["power.capacitor-loss","W"],["power.conduction-loss","W"],["power.controller-or-quiescent-loss","W"],["power.efficiency","1"],["power.feedback-loss","W"],["power.gate-drive-loss","W"],["power.hottest-junction-temperature","K"],["power.inductor-copper-loss","W"],["power.inductor-core-loss","W"],["power.inductor-ripple-current","A"],["power.loop-phase-margin","1"],["power.output-ripple","V"],["power.switching-loss","W"],["power.total-loss","W"],
].map(([id,unit])=>({id:id!,unit:unit! as ElectricalMetricDeclarationV2["unit"]})).sort((a,b)=>compareDesignV2Tokens(a.id,b.id));
const legacyProfileIdentities:LegacyProfileIdentityV2[]=[
  ...SYNTHETIC_BUCK_TEST_CATALOG.integratedRegulators.map((profile)=>({profileId:profile.profileId,partClass:"power.integrated-synchronous-buck-regulator" as const,part:profile.part})),
  ...SYNTHETIC_BUCK_TEST_CATALOG.externalControllers.map((profile)=>({profileId:profile.profileId,partClass:"power.external-fet-synchronous-buck-controller" as const,part:profile.part})),
  ...SYNTHETIC_BUCK_TEST_CATALOG.mosfets.map((profile)=>({profileId:profile.profileId,partClass:"shared.n-channel-power-mosfet" as const,part:profile.part})),
  ...SYNTHETIC_BUCK_TEST_CATALOG.inductors.map((profile)=>({profileId:profile.profileId,partClass:"power.power-inductor" as const,part:profile.part})),
  ...SYNTHETIC_BUCK_TEST_CATALOG.resistors.map((profile)=>({profileId:profile.profileId,partClass:"shared.general-purpose-resistor" as const,part:profile.part})),
  ...SYNTHETIC_BUCK_TEST_CATALOG.capacitors.map((profile)=>({profileId:profile.profileId,partClass:"shared.mlcc-capacitor" as const,part:profile.part})),
];
const ADAPTED_RECIPES=BUCK_RECIPES.map((recipe)=>adaptDesignRecipeV1ToV2(recipe,{applications:["power.buck"],metricDeclarations:declarations,legacyProfileIdentities})).sort((a,b)=>compareDesignV2Tokens(a.id,b.id));
const powerPareto:ElectricalRankingPolicyV2["paretoCriteria"]=[{source:"metric",metricId:"power.board-area",direction:"minimize"},{source:"metric",metricId:"power.efficiency",direction:"maximize"}];
const policyPayload:Omit<ElectricalRankingPolicyV2,"contentHash">={format:"schemagic-electrical-ranking-policy",schemaVersion:2,version:"power-electrical-ranking-v2.1",application:"power.buck",paretoCriteria:powerPareto,rankingProfiles:{area:[{source:"metric",metricId:"power.board-area",direction:"minimize"},{source:"metric",metricId:"power.efficiency",direction:"maximize"}],balanced:[{source:"metric",metricId:"power.efficiency",direction:"maximize"},{source:"metric",metricId:"power.board-area",direction:"minimize"},{source:"metric",metricId:"power.hottest-junction-temperature",direction:"minimize"}],efficiency:[{source:"metric",metricId:"power.efficiency",direction:"maximize"},{source:"metric",metricId:"power.hottest-junction-temperature",direction:"minimize"}],temperature:[{source:"metric",metricId:"power.hottest-junction-temperature",direction:"minimize"},{source:"metric",metricId:"power.efficiency",direction:"maximize"}]}};
const TEST_RANKING_POLICY={...policyPayload,contentHash:calculateElectricalRankingPolicyV2ContentHash(policyPayload)};

type LocalProfile={part:{manufacturerId:string;manufacturerPartNumber:string}};
function profile(partClass:PartClassId,source:LocalProfile):DesignProfileV1{return{format:"schemagic-design-profile",schemaVersion:"1.0.0",partClass,part:source.part,factsSchemaVersion:"1.0.0",commonFacts:{} as never,facts:{}};}
function syntheticProfiles():DesignProfileV1[]{const profiles:DesignProfileV1[]=[];SYNTHETIC_BUCK_TEST_CATALOG.integratedRegulators.forEach((entry)=>profiles.push(profile("power.integrated-synchronous-buck-regulator",entry)));SYNTHETIC_BUCK_TEST_CATALOG.externalControllers.forEach((entry)=>profiles.push(profile("power.external-fet-synchronous-buck-controller",entry)));SYNTHETIC_BUCK_TEST_CATALOG.mosfets.forEach((entry)=>profiles.push(profile("shared.n-channel-power-mosfet",entry)));SYNTHETIC_BUCK_TEST_CATALOG.inductors.forEach((entry)=>profiles.push(profile("power.power-inductor",entry)));SYNTHETIC_BUCK_TEST_CATALOG.resistors.forEach((entry)=>profiles.push(profile("shared.general-purpose-resistor",entry)));SYNTHETIC_BUCK_TEST_CATALOG.capacitors.forEach((entry)=>profiles.push(profile("shared.mlcc-capacitor",entry)));return profiles.sort((a,b)=>compareDesignV2Tokens(designProfileId(a.partClass,a.part),designProfileId(b.partClass,b.part)));}
export function createSyntheticPowerDesignContextV2ForTesting(version="designer-v1-reference.1"):GenerateElectricalTestContextV2{const sourceRelease={version,contentHash:("sha256:"+"2".repeat(64)) as `sha256:${string}`};const catalogPayload:Omit<ReviewedProfileCatalogV2,"contentHash">={format:"schemagic-reviewed-profile-catalog",schemaVersion:2,version,sourceRelease,profiles:syntheticProfiles()};const catalog={...catalogPayload,contentHash:calculateReviewedProfileCatalogV2ContentHash(catalogPayload)};const manifestPayload:Omit<ElectricalDesignContextManifestV2,"contentHash">={format:"schemagic-electrical-design-context",schemaVersion:2,version,application:"power.buck",compiler:getInstalledCompilerImplementationRefV2(),catalog:{version,contentHash:catalog.contentHash,sourceReleaseContentHash:sourceRelease.contentHash},rankingPolicy:{version:TEST_RANKING_POLICY.version,contentHash:TEST_RANKING_POLICY.contentHash},recipes:ADAPTED_RECIPES.map(({id,version:recipeVersion,contentHash,applications,metricDeclarations})=>({id,version:recipeVersion,contentHash,applications,metricDeclarations}))};const manifest={...manifestPayload,contentHash:calculateElectricalDesignContextManifestV2ContentHash(manifestPayload)};return{testOnly:true,manifest,catalog,rankingPolicy:TEST_RANKING_POLICY,recipes:ADAPTED_RECIPES};}
export function generateSyntheticBuckDesignV2ForTesting(request:BuckDesignRequestV2):DesignGenerationV2{return generateElectricalDesignV2ForTesting(request,createSyntheticPowerDesignContextV2ForTesting(request.libraryVersion));}
